### PR TITLE
Update DSP/FFTW, Travis, and put Plots behind Requires

### PR DESCRIPTION
**Pull request by Datseris**
At the moment this package has troubles being installed and working properly because of outdated DSP versions (and thus FFTW). I have updated this here.

In addition I have updated the Travis scripts to run windows (and commented out nightlies, feel free to enable them again). 

Lastly, I've added Plots behind the Requires block: this reduces the major installation bottleneck of adding Plots+GR+dependencies. If you accept this I'll add a note on the documentation about it.

@kahaaga please have a look at this PR, so it is again possible to use TimeseriesSurrogates with the stable versions of FFTW/DSP.

### CODE REVIEW

**Comment by Datseris** [comment]
In addition, you should consider using CompatHelper.jl

**Comment by kahaaga** [comment]
Hey there @Datseris! Thanks for the PR - this looks good. It was silly of me not to use `Requires` to begin with. 

Before I merge, if you don't mind, could you add a small note on having to load Plots manually in the documentation?

**Comment by Datseris** [comment]
Of course, I am on it.

**Comment by Datseris** [comment]
I did some more changes: 

1. removed `REQUIRE` and `Manifest.toml` as neither are required anymore (and Manifest.toml is an always outdated file, better to not include it at all).
2. Increased the version to 0.5 instead, because technically this is a breaking change.

**Comment by Datseris** [comment]
As I was reading the docs I realized that the documentation of TimeseriesSurrogates.jl is actually created in two different places. In this package but also here: https://kahaaga.github.io/CausalityTools.jl/dev/surrogates/surrogates_overview/  having several productions of a documentation makes it a bit harder to maintain, so it is probably worth it for you to consider which of the two versions you want to keep and use only this one.

**Comment by Datseris** [comment]
(my personal suggestion btw would be to let TimeseriesSurrogote.jl have its own dedicated documentation, because it is useful enough as a standalone)

**Comment by kahaaga** [comment]
Good point on the documentation. I haven't been entirely sure how to organise the docs for the surrogates. I've avoided taking a decision pending the implementation of some new surrogate methods  I've developed (that are specific to causality testing). These are supposed to be added somewhere in the ecosystem, but I'm not sure whether they belong in this package (which is more general), or in CausalityTools (specific to surrogate testing). I think I favour the latter. 

Therefore, I think I agree with you on keeping the documentation as is her, and keeping causality-specific stuff in CausalityTools, which can keek track of additional documentation specific to causality testing.

**Comment by kahaaga** [comment]
The documentation looks nice! Thanks.

**Comment by kahaaga** [comment]
@Datseris TimeseriesSurrogates v0.5.0 is now in the registry, so hopefully everything should work with the latest versions of DSP and FFTW.

**Pull request merged**
